config/routes.rb
Rails.application.routes.draw do
  resources :albums, only: [:index, :create, :new] do
    resources :images, only: [:new, :create]
  end
  root 'static_pages#home'

  devise_for :users, controllers: { omniauth_callbacks: 'auth/callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.create_from_omniauth(params)
    user = find_or_create_by(email: params.info.email, uid: params.uid)
    me = Facebook.get_object(params.credentials.token, "me", fields:'link')
    user.update({
      token: params.credentials.token,
      name: params.info.name,
      avatar: params.info.image,
      link: me["link"]
    })
    user
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  require 'date'
  def index
    @albums = Facebook.get_albums(current_user)
    @albums.first(2).each do |album|
      # album.merge!(likes: Facebook.get_object(current_user.token, "#{album["id"]}/likes", fields:'total_count,summary(true)'))
      # p album[:likes]
      album.merge!(comments: Facebook.get_object(current_user.token, "#{album["id"]}/comments"))
      if album["cover_photo"]
        album.merge!(cover: Facebook.get_image(current_user, album["cover_photo"]["id"]))
      end
      p album[:cover]
    end
  end
  def new

  end
  def create
    @album = Facebook.create_albums(current_user, params[:title])
    params[:img].each do |img|
      type = file_type(img)
      if type.match(/image\/*/)
        @image = Facebook.create_image(current_user, album_id, img)
      elsif type.match(/video\/*/)
        @image = Facebook.create_video(current_user, album_id, img)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token  
  include ApplicationHelper
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
  end
  def create
    album_id = params[:album_id]
    params[:img].each do |img|
      type = file_type(img)
      if type.match(/image\/*/)
        @image = Facebook.create_image(current_user, album_id, img)
      elsif type.match(/video\/*/)
        @image = Facebook.create_video(current_user, type, "me", img)
      end
    end
    redirect_to albums_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def strtodate(str)
    date = Date.parse str
  end

  def content_preview(content)
    if content
      if(content.length > 100)
        content[0..99] + " ..."
      else
        content
      end
    end
  end
end

app/helpers/application_helper.rb
require 'mimemagic'
module ApplicationHelper
  def file_type(file)
    if file.respond_to?(:read)
      MimeMagic.by_magic(file.read).type
    elsif file_data.respond_to?(:path)
      MimeMagic.by_magic(File.open(file.path)).type
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/albums/_album.html.erb
<%= link_to album.name, album.link %>

app/views/albums/index.html.erb
<%= link_to new_album_path, class: "btn btn-primary center" do %>
  <i class="fa fa-plus"></i> New album
<% end %>
<section id="blog" class="section blog">
  <div class="container">
    <div id="blogContent" class="section-content">
      <div class="row">
        <% @albums.first(2).each do |album| %>
        <% if true %>
        <div class="col-sm-6 col-md-4">
          <div class="blog-post">
            <header>
              <h4 class="date"><%= I18n.t("abbr_month_names")[strtodate(album["created_time"]).month] %><hr><%= strtodate(album["created_time"]).year %></h4>
              <div class="blog-element">
                <% if album[:cover] %>
                <%= image_tag album[:cover]["images"][0]["source"], class:"img-fluid" %>
              <% else %>
                <%= image_tag image_url("placeholder.png"), class:"img-fluid" %>
                <% end %>
              </div>
            </header>
            <div class="blog-content">
              <h4>
                <%= link_to album["name"], album["link"], target:"_blank" %>
              </h4>
              <div class="post-meta">
                <span>By
                  <%= link_to current_user.name, current_user.link, target:"_blank" %>
                </span>
                <span>
                  <a href="#"><%= album[:comments].length %>
                    Comments</a>
                </span>
              </div>
              <% if album["cover_photo"] && album["cover_photo"]["name"] %>
              <p><%= content_preview(album["cover_photo"]["name"]) %></p>
            <% else %>
              <p>No caption yet</p>
              <% end %>
              <%= link_to new_album_image_path(album["id"]), class: "btn btn-primary" do %>
              <i class="fa fa-plus"></i> New image
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/albums/new.html.erb
<div class="container">
  <div class="row">
    <form action="/albums" method="post" enctype="multipart/form-data">
      <input type="text" class="form-control" name="title" placeholder="Album title">
      <input type="file" class="form-control" name="img[]" multiple accept="image/*">
      <input type="submit" class="btn btn-primary">
    </form>
  </div>  
</div>

app/views/common/_header.html.erb
<header id="header" class="home-parallax home-fade header-inner">
  <div class="my-title">
    <h1>Album Collection</h1>
  </div>
</header>

app/views/images/new.html.erb
<div class="row">
  <form action="/albums/<%= params[:album_id] %>/images" method="post" enctype="multipart/form-data">
    <input type="file" class="form-control" name="img[]" multiple accept="image/*">
    <input type="submit" class="btn btn-primary">
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Album Collection</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'common/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="container logincard">
  <%= link_to user_facebook_omniauth_authorize_url(),
      class: "btn btn-lg btn-fb" do %>
    <i class="fa fa-facebook-square"></i> Connect with Facebook
  <% end %>
  <%= link_to user_facebook_omniauth_authorize_url(),
      class: "btn btn-lg btn-insta" do %>
    <i class="fa fa-instagram"></i> Connect with Instagram
  <% end %>
</div>